version: "3.8"
services:
  mongodb:
    image : mongo
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./mongodb/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped

  server:
    build: server
    ports: [3000]
    restart: always
    volumes:
      - ./server:/app